from concurrent.futures import ThreadPoolExecutor, as_completed

from business_context import build_business_context
from foundary_client import project_client

from agents.analytics import analyze as analytics
from agents.finance_agent import analyze as finance
from agents.market_agent import analyze as market
from agents.customer_agent import analyze as customer
from agents.risk_agent import assess
from agents.strategy_agent import recommend


MANAGER_AGENT = "Synapse-Manager-Agent"


# ==========================================
# MANAGER FINAL REPORT
# ==========================================

def manager_final_report(
    question: str,
    findings: dict,
    business_context: str
) -> str:

    openai = project_client.get_openai_client(
        agent_name=MANAGER_AGENT
    )

    findings_text = ""

    for agent, result in findings.items():

        findings_text += (
            f"\n\n===== {agent.upper()} =====\n"
        )

        findings_text += str(result)

    prompt = f"""
You are the Manager Agent of Synapse.

You are responsible for producing the final business report
for the user.

Business question:
{question}

BUSINESS CONTEXT:
{business_context}

The following reports were generated by the specialist agents:

{findings_text}

IMPORTANT:
- Treat the BUSINESS CONTEXT as the authoritative baseline.
- The uploaded business files are the source of truth.
- Use only information provided by the business context
  and specialist agents.
- Do not invent numbers or facts.
- Do not silently resolve conflicting information.
- If two agents provide conflicting information, explicitly
  mention the conflict in the report.
- Preserve important numerical findings.
- Clearly distinguish evidence from assumptions.
- Do not substitute another time period.
- Do not repeat the same point unnecessarily.
- Prioritize the most important business issues.
- Make recommendations actionable.
- Include relevant KPIs where available.

Create a final, clear and professional business report.

Structure the report as:

1. Executive Summary
2. Key Findings
3. Financial Insights
4. Sales & Analytics
5. Market Insights
6. Customer Insights
7. Risk Assessment
8. Strategic Recommendations
9. Missing Information / Assumptions
10. Next Steps

Return only the final business report.

DATA CONSISTENCY RULE:

When different agents report different numerical values
for the same metric or period:

1. Do not choose a value arbitrarily.
2. Identify the conflicting values.
3. State which source reported each value.
4. Treat the conflict as missing/inconsistent data.
5. Do not calculate conclusions using an unresolved value.

The final report must preserve the distinction between
verified data and conflicting data.

EVIDENCE RULES:

- Only report a numerical value if it appears in the supplied
  agent findings or business context.
- Do not infer the cause of a metric unless the evidence
  explicitly supports that cause.
- Do not convert correlation into causation.
- If an agent makes an unsupported claim, label it as an
  inference or omit it from the final report.
- Never invent missing breakdowns.
- When evidence is insufficient, say "Insufficient data."
"""

    response = openai.responses.create(
        input=prompt
    )

    return response.output_text


# ==========================================
# MAIN ORCHESTRATOR
# ==========================================

def run_analysis(
    question: str,
    context: str = "",
    business_id: str = None
):

    print("\n🚀 Starting Synapse Analysis...\n")

    # -----------------------------------
    # Validate Business ID
    # -----------------------------------

    if not business_id:
        raise ValueError(
            "business_id is required for business-isolated analysis."
        )

    print(f"🏢 Business ID: {business_id}")

    # -----------------------------------
    # Build context ONLY for this business
    # -----------------------------------

    business_context = build_business_context(
        business_id
    )

    # -----------------------------------
    # STEP 1: Specialist Agents
    # -----------------------------------

    specialists = {
        "analytics": analytics,
        "finance": finance,
        "market": market,
        "customer": customer
    }

    findings = {}

    print("\nRunning specialist agents...")

    combined_context = f"""
BUSINESS ID:
{business_id}

BUSINESS CONTEXT:
{business_context}

ADDITIONAL CONTEXT:
{context}
"""

    with ThreadPoolExecutor(max_workers=4) as executor:

        futures = {
            executor.submit(
                agent_function,
                question,
                combined_context,
                business_id
            ): agent_name

            for agent_name, agent_function
            in specialists.items()
        }

        for future in as_completed(futures):

            agent_name = futures[future]

            try:

                result = future.result()

                findings[agent_name] = result

                print(
                    f"✅ {agent_name.capitalize()} Agent completed"
                )

            except Exception as e:

                findings[agent_name] = (
                    f"Agent failed: {str(e)}"
                )

                print(
                    f"❌ {agent_name.capitalize()} Agent failed: {str(e)}"
                )

    # -----------------------------------
    # STEP 2: Risk Agent
    # -----------------------------------

    print("\nRunning Risk Agent...")

    risk = assess(
        question,
        findings,
        business_id
    )

    findings["risk"] = risk

    print("✅ Risk Agent completed")

    # -----------------------------------
    # STEP 3: Strategy Agent
    # -----------------------------------

    print("\nRunning Strategy Agent...")

    strategy = recommend(
        question,
        findings,
        business_id
    )

    findings["strategy"] = strategy

    print("✅ Strategy Agent completed")

    # -----------------------------------
    # STEP 4: Manager Final Synthesis
    # -----------------------------------

    print("\nRunning Manager Agent for final synthesis...")

    final_report = manager_final_report(
        question=question,
        findings=findings,
        business_context=business_context
    )

    print("✅ Manager Agent completed")

    # -----------------------------------
    # STEP 5: Final Result
    # -----------------------------------

    return {
        "question": question,
        "business_id": business_id,
        "findings": findings,
        "risk": risk,
        "strategy": strategy,
        "final_report": final_report
    }